apiVersion: v1
data:
# Helm loads files from the etc dir
{{ (.Files.Glob "etc/*").AsConfig | indent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "garage-server.fullname" . }}-conf
  annotations:
  {{- range $i, $e := .Chart.Sources }}
    github-url-{{ $i }}: {{ $e }}
  {{- end }}
